name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: bluefunda/release-foundry/.github/workflows/go-docker-deploy.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
